version: 2.1

orbs:
  node: circleci/node@5

workflows:
  test_my_app:
    jobs:
      - build_and_test:
          context: admin

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Create .env.testing"
          command: |
            echo "BASE_PATH=${BASE_PATH}" > .env.testing
            echo "PORT=${PORT}" >> .env.testing
            echo "TURSO_DATABASE_URL=${TURSO_DATABASE_URL}" >> .env.testing
            echo "TURSO_DATABASE_AUTH_TOKEN=${TURSO_DATABASE_AUTH_TOKEN}" >> .env.testing
            echo "SESSION_SECRET=${SESSION_SECRET}" >> .env.testing
            echo "NODE_ENV=${NODE_ENV}" >> .env.testing
      - run: npm install cross-env
      - run: npm install
      - run: npm test