version: 2.1

orbs:
  node: circleci/node@5

workflows:
  test:
    jobs:
      - build_and_test:
          context: admin

jobs:
  build_and_test:
    docker:
      - image: cimg/node:21.5.0
        environment:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: 'Download public key'
          command: curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add 
      - run:
          name: Install Redis
          command: sudo apt-get update && sudo apt-get install -y redis-server
      - run:
          name: Start Redis Server
          command: sudo service redis-server start
      - run:
          name: Test Redis Connection
          command: |
            redis-cli ping || echo "Redis connection failed"
      - run:
          name: Check Redis Logs
          command: sudo cat /var/log/redis/redis-server.log
      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo $BASE_PATH
            echo $PORT
            echo $TURSO_DATABASE_URL
            echo $TURSO_DATABASE_AUTH_TOKEN
            echo $SESSION_SECRET
            echo $NODE_ENV
      - run: npm install cross-env
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test